const express = require("express");
const path = require("path");
require("dotenv").config();

const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.json());
app.use(express.static(path.join(__dirname, "frontend")));

app.post("/api/gemini-chat", async (req, res) => {
  try {
    const { question, context } = req.body;

    if (!process.env.GEMINI_API_KEY) {
      return res.status(500).json({
        error: "Missing GEMINI_API_KEY in environment variables."
      });
    }

    const prompt = `
You are a logistics assistant for a hackathon MVP called "Damm Smart Truck".
Your role is to answer clearly and professionally about the project.

Project context:
${JSON.stringify(context, null, 2)}

User question:
${question}

Instructions:
- Answer in a concise but professional way.
- Focus on logistics, route planning, load planning and operational impact.
- If the question is about the MVP, explain the logic clearly.
- If the answer cannot be fully known, say that it is based on the current demo context.
`;

    const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${process.env.GEMINI_API_KEY}`;

    const geminiResponse = await fetch(apiUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              { text: prompt }
            ]
          }
        ]
      })
    });

    const data = await geminiResponse.json();

    const reply =
      data?.candidates?.[0]?.content?.parts?.[0]?.text ||
      "No response generated by Gemini.";

    res.json({ reply });
  } catch (error) {
    console.error("Gemini API error:", error);
    res.status(500).json({ error: "Error connecting to Gemini API." });
  }
});

app.get("/", (req, res) => {
  res.sendFile(path.join(__dirname, "frontend", "dashboard.html"));
});

app.listen(PORT, () => {
  console.log(`Server running on http://localhost:${PORT}`);
});